### ISSUE TITLE
ContextShift instance

### ISSUE THREAD

**Issue by ben-healthforge** [travisbrown/catbird#157]
It would be useful to have a `ContextShift` instance as a generic alternative to `FuturePool` (eg for blocking io).  I think that `evalOn` would fulfil this role and should behave essentially as `FuturePool` does now.

I'm not sure what `shift` should do though.  It seems like the main relevant use case  would be to improve fairness on cpu-bound work running on a small pool of threads.  It could do this by:
* calling `Scheduler.flush()` - doesn't switch threads and I think is dangerous to do a lot because it adds stack frames
* constructing the `ContextShift` instance with a thread pool intended for this purpose and having `shift` switch between threads on that pool - but it seems wrong to force the user to provide this pool if all they want to do is use `evalOn`

**Comment by felixbr** [comment]
As I undertand it `ContextShift` is `cats-effect` way to define the main thread pool of an application plus a way to temporarily switch to a different one (via `evalOn` and `blockOn`). `shift` is used to go back to the default thread pool.

Do you have a concrete use-case for this? To me it seems mostly useful if you want to call out into an `fs2` library while still using twitter futures or `Rerunnable`. I'm not sure how easy it is to get ahold of the default thread-pool of a typical finagle application to construct the `ContextShift` instance..

**Comment by dangerousben** [comment]
This can be closed, but either the github UI is beyond my meagre human intellect or I don't have access to do so :)
