### ISSUE TITLE
Decide when to drop 2.11 support

### ISSUE THREAD

**Issue by travisbrown** [travisbrown/catbird#213]
The Cats and cats-effect 2.0.0 releases are almost six months old. We have 2.1 releases for both, and will have Cats 2.2.0 soon, and none of these support Scala 2.11. Finch is likely to drop Scala 2.11 before long ([e.g.](https://github.com/finagle/finch/pull/1204)).

There's no particular reason that's come up for us to drop 2.11 here yet, but as soon as it becomes a burden I'm ready to let it go. If someone really needs it, please let us know.

**Comment by brbrown25** [comment]
@travisbrown I'm willing to pick this up.
