### ISSUE TITLE
Finagle Upgrade

### ISSUE THREAD

**Issue by mishriky** [travisbrown/catbird#453]
Are there any plans for upgrading Finagle to the most recent version: `22.3.0` ? 
I can potentially look into taking on the changes if I can get support in getting the PR reviewed/merged/released

@bpholt tagging you since you seem to be active on the repo

**Comment by mishriky** [comment]
Created a PR here: https://github.com/typelevel/catbird/pull/454

**Comment by bpholt** [comment]
Thanks! There were some changes made in `21.9.0` that may cause issues, so I'd like to look at those before we merge. (I'm away from my computer at the moment or I'd be more specific.)

Also, I think technically Twitter released `22.4.0`, but there were no changes from `22.3.0`. We may still want to go to that version to facilitate eventually having Scala Steward initiate these kinds of updates.

**Comment by armanbilge** [comment]
This is now available in `22.4-380e14a-SNAPSHOT`.
https://s01.oss.sonatype.org/content/repositories/snapshots/org/typelevel/catbird-effect_2.13/22.4-380e14a-SNAPSHOT/

**Comment by bpholt** [comment]
I think with the changes in #460 and #461 (which incorporated #454), we should be able to release `22.4.0`. I plan to draft release notes tonight or tomorrow, and the release itself will happen shortly after those are published. Thanks for your contribution and patience!

**Comment by bpholt** [comment]
[`v22.4.0`](https://github.com/typelevel/catbird/releases/tag/v22.4.0) is on its way to Maven Central now!
