### ISSUE TITLE
Conflicts with com.twitter.bijection.twitter_util.UtilBijections._?

### ISSUE THREAD

**Issue by omerzach** [travisbrown/catbird#59]
I have a file that uses `com.twitter.bijection.twitter_util.UtilBijections._` with `com.twitter.bijection.Conversion.asMethod` extensively to convert from `com.twitter.util.Future` to `scala.concurrent.Future`.

I'm introducing cats' `EitherT` into that file to be used with `com.twitter.util.Future`s and need a `cats.Functor[com.twitter.util.Future]` to do that so I added `import io.catbird.util._`.

Unfortunately it seems to conflict with bijection somehow, giving me errors like this on each use of the bijection conversion:
```
                       [error] /Users/omer/code/sigma-monorepo/src/jvm/com/thesigma/server/graphql/schema/main/SigmaSchema.scala:2206: missing argument list for method as in trait Ops
                       [error] Unapplied methods are only converted to functions when a function type is expected.
                       [error] You can make this conversion explicit by writing `as _` or `as(_)` instead of `as`.
                       [error]           ).as[ScalaFuture[Connection[OrgActivity]]]
```

`ScalaFuture` here is `scala.concurrent.Future` and `as` is being called on something with type `com.twitter.util.Future[Connection[OrgActivity]]`.

I don't see another `as` defined anywhere in the catbird source so have no clue where to start trying to fix this. Any suggestions? I can create a small repo demonstrating the issue if it's helpful/necessary. Thanks!

**Comment by omerzach** [comment]
Ah I see cats' `Functor` has an `as` method that must be causing the conflict

**Comment by travisbrown** [comment]
Yes, unfortunately I think your best bet is probably forgoing one of the syntax imports in that scope.

**Comment by omerzach** [comment]
Yep I got rid of the Bijection implicits and things are working now. Thanks!
